# These outputs work with both 'terraform output' and 'tofu output'
output "random_string" {
  description = "A random string (same behavior with terraform and tofu)"
  value       = random_string.compatible_example.result
}

output "friendly_name" {
  description = "A friendly random name"
  value       = random_pet.friendly_name.id
}

output "tool_note" {
  description = "A note about tool compatibility"
  value       = "This output was generated by OpenTofu OR Terraform - the code is identical!"
}
